// FOLDERS
export './model/xcore.dart';
export './page/xcore.dart';
export './services/xcore.dart';
// PLUGINS
export 'package:flutter/material.dart';
export 'package:get/get.dart';
export 'dart:convert';
export 'package:equatable/equatable.dart';
